### PR TITLE
Update version in Gemfile.lock to 1.34.0

### PR DESCRIPTION
**Pull request by pbomb**
The last commit did not trigger a release. Perhaps this change needs to be made?

### CODE REVIEW

**Comment by pbomb** [comment]
@alexevanczuk Can you take a look at this?

**Comment by alexevanczuk** [comment]
Ah yeah, I think you actually need to bump the patch version once and then `bundle install` so CI + CD picks this up as a new release.

(We probably should have a CI check to ensure `bundle install` is run once a version is updated!)

**Comment by alexevanczuk** [comment]
Sorry about all the hassle @pbomb

**Comment by pbomb** [comment]
@alexevanczuk I'm confused. What do I need to do now? `bundle install` doesn't lead to any new changes.

**Comment by pbomb** [comment]
@alexevanczuk okay, done

**Comment by alexevanczuk** [comment]
@pbomb You should be good now https://github.com/rubyatscale/code_ownership/releases/tag/v1.34.1

**Pull request merged**
